services:

  db-cassandra:
    image: cassandra:5.0.6
    container_name: url-shortener-db-cassandra
    environment:
      CASSANDRA_USER: admin
      CASSANDRA_PASSWORD: admin
      CASSANDRA_DB: urlShortenerDB
    ports:
      - "9042:9042"
    volumes:
      - db-cassandra-vol:/var/lib/cassandra/data
    networks:
      - url-shortener-network

  redis:
    image: redis:8.4.0
    container_name: url-shortener-redis
    ports:
      - 6379:6379
    networks:
      - url-shortener-network

  backend:
    build:
      context: ./url-redirect-service
      dockerfile: Dockerfile
    container_name: url-redirect-service
    ports:
      - 9091:8080
    depends_on:
      - db-cassandra
      - redis

volumes:
  db-cassandra-vol:

networks:
  url-shortener-network:
    driver: bridge
