spring.application.name=url-shortening-service
server.port=8090

# Cassandra Configuration
spring.cassandra.contact-points=${CASSANDRA_CONTACT_POINT:localhost}
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=urlShortenerDB
spring.cassandra.schema-action=create_if_not_exists
# spring.cassandra.username=admin
# spring.cassandra.password=admin

# 
logging.level.com.datastax.oss.driver=DEBUG
logging.level.org.springframework.data.cassandra=DEBUG

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

eureka.instance.hostname=localhost