spring.application.name=url-shortener-gateway-api

server.port=8080

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.server.adapter=TRACE

# Gateway Discovery Locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route Configuration - User Service
spring.cloud.gateway.routes[0].id=url-shortening-service
spring.cloud.gateway.routes[0].uri=lb://url-shortening-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/url/**
spring.cloud.gateway.routes[0].predicates[1]=Method=POST,PUT,DELETE
spring.cloud.gateway.routes[0].filters[0]=AddRequestHeader=X-Gateway-Request, Gateway

# Route Configuration - Product Service
spring.cloud.gateway.routes[1].id=url-redirect-service
spring.cloud.gateway.routes[1].uri=lb://url-redirect-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/url/**
spring.cloud.gateway.routes[1].predicates[1]=Method=GET
spring.cloud.gateway.routes[1].filters[0]=AddRequestHeader=X-Gateway-Request, Gateway


# CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600

# Default Filters - Retry
spring.cloud.gateway.default-filters[0]=Retry=3, SERVER_ERROR, GET, POST

# Actuator Configuration
management.endpoints.web.exposure.include=gateway,health,info,metrics
management.endpoint.gateway.enabled=true
management.endpoint.health.show-details=always




# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

