spring.application.name=url-redirect-service
server.port=9091

# Cassandra Configuration
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=urlShortenerDB
spring.cassandra.schema-action=create_if_not_exists
# spring.cassandra.username=admin
# spring.cassandra.password=admin

logging.level.com.datastax.oss.driver=DEBUG
logging.level.org.springframework.data.cassandra=DEBUG